spring:
  application:
    name: CreditLimitTracker
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

prn:
  fixedStartingPositions: 16,38,47,61,74,82
